name: PR Preview Deploys
description: Easy PR Preview Deploy UX
inputs:
  step:
    description: start, finish, or cleanup
    required: true
  env:
    description: Environment
    required: true
  env_url:
    description: Environment URL. Required during 'finish' step.
  head_ref:
    description: "`github.head_ref`. Required during 'start' step."
  status:
    description: "`job.status`. Required during 'finish' step."
  deployment_id:
    description: Required during 'finish' step.
  app_id:
    description: |
      ID of a GitHub App installed on this repo with repo Administration permissions.
      Required during 'cleanup' step.
    default: ""
  app_pem:
    description: |
      Private Key from the above GitHub App installation.
      Required during 'cleanup' step.
    default: ""
  token:
    description: |
      A Github token. `secrets.GITHUB_TOKEN`` is fine for start and finish steps.
    default: ""

outputs:
  deployment_id:
    description: "ID of deployment created during start step."
    value: ${{ steps.deployment.outputs.deployment_id }}

runs:
  using: "composite"
  steps:
    - name: Get token
      if: ${{ inputs.token == '' && inputs.app_id != '' && inputs.app_pem != '' }}
      uses: tibdex/github-app-token@v1.8.0
      id: token
      with:
        app_id: ${{ inputs.app_id || 'unset' }}
        private_key: ${{ inputs.app_pem || 'unset' }}

    - name: Determine deployment log URL
      if: ${{ inputs.step == 'start' || inputs.step == 'finish' }}
      uses: actions/github-script@v6
      id: job-url
      with:
        script: |
            const { data } = await github.rest.actions.listJobsForWorkflowRunAttempt({
              ...context.repo,
              run_id: context.runId,
              attempt_number: process.env.GITHUB_RUN_ATTEMPT,
            });

            return data.jobs[0].html_url
        result-encoding: string

    - name: Start deployment
      if: ${{ inputs.step == 'start' }}
      uses: bobheadxi/deployments@v1
      id: deployment
      with:
        step: start
        token: ${{ steps.token.outputs.token != '' && steps.token.outputs.token || inputs.token }}
        ref: ${{ inputs.head_ref }}
        logs: ${{ steps.job-url.outputs.result }}
        env: preview-${{ github.event.pull_request.number }}

    - name: Finish deployment
      if: ${{ inputs.step == 'finish' }}
      uses: bobheadxi/deployments@v1
      with:
        step: finish
        token: ${{ steps.token.outputs.token != '' && steps.token.outputs.token || inputs.token }}
        ref: ${{ github.head_ref }}
        logs: ${{ steps.job-url.outputs.result }}
        deployment_id: ${{ inputs.deployment_id }}
        status: ${{ inputs.status }}
        env: ${{ inputs.env }}

        env_url: https://pr-preview-${{ github.event.pull_request.number }}.example.com

    - name: Mark deployments as deactivated
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
      uses: bobheadxi/deployments@v1
      with:
        step: deactivate-env
        token: ${{ steps.token.outputs.token != '' && steps.token.outputs.token || inputs.token }}
        env: preview-${{ github.event.pull_request.number }}
        desc: PR was closed

    - name: Delete environment
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
      uses: actions/github-script@v6
      env:
        ENVIRONMENT_TO_DELETE: preview-${{ github.event.pull_request.number }}
      with:
        github-token: "${{ steps.token.outputs.token }}"
        result-encoding: string
        script: |
            const { data } = await github.rest.repos.deleteAnEnvironment({
              ...context.repo,
              environment_name: process.env.ENVIRONMENT_TO_DELETE
            });
            console.log(data);

